name: 每六小時運行爬蟲程式

on:
  schedule:
    - cron: "0 */6 * * *"  # 這個 cron 表示每六小時執行一次
  workflow_dispatch:  # 允許手動從 GitHub UI 執行

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # 步驟 1: 檢出程式碼
      - name: 檢出程式碼
        uses: actions/checkout@v3

      # 步驟 2: 設定 Python 環境
      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 指定 Python 版本

      # 步驟 3: 安裝依賴（可選）
      - name: 安裝依賴
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果你有 requirements.txt 文件

      # 步驟 4: 執行 Python 腳本
      - name: 執行 Python 腳本
        run: |
          python house.py  # 替換為你的腳本名稱
